'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''lblTanggal0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTanggal0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTanggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTanggal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbIdCs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbIdCs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCek As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbNamaBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNamaBrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHitung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHitung As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbHargaBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHargaBrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSimpanData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimpanData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlAsal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAsal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbTujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTujuan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbTarif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTarif As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbMetode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMetode As Global.System.Web.UI.WebControls.RadioButtonList
End Class
